/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWatchlistRouteImport } from './routes/app.watchlist'
import { Route as AppSimulatorRouteImport } from './routes/app.simulator'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppOptionsRouteImport } from './routes/app.options'
import { Route as AppMarketsRouteImport } from './routes/app.markets'
import { Route as AppMarginRouteImport } from './routes/app.margin'
import { Route as AppJournalRouteImport } from './routes/app.journal'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as AppStockSymbolRouteImport } from './routes/app.stock.$symbol'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppOptionsRoute = AppOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppMarginRoute = AppMarginRouteImport.update({
  id: '/margin',
  path: '/margin',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppStockSymbolRoute = AppStockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/app/agent': typeof AppAgentRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal': typeof AppJournalRoute
  '/app/margin': typeof AppMarginRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/options': typeof AppOptionsRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/': typeof AppIndexRoute
  '/app/stock/$symbol': typeof AppStockSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/app/agent': typeof AppAgentRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal': typeof AppJournalRoute
  '/app/margin': typeof AppMarginRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/options': typeof AppOptionsRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app': typeof AppIndexRoute
  '/app/stock/$symbol': typeof AppStockSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/app/agent': typeof AppAgentRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal': typeof AppJournalRoute
  '/app/margin': typeof AppMarginRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/options': typeof AppOptionsRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/': typeof AppIndexRoute
  '/app/stock/$symbol': typeof AppStockSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/simulator'
    | '/terms'
    | '/app/agent'
    | '/app/dashboard'
    | '/app/journal'
    | '/app/margin'
    | '/app/markets'
    | '/app/options'
    | '/app/portfolio'
    | '/app/settings'
    | '/app/simulator'
    | '/app/watchlist'
    | '/app/'
    | '/app/stock/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/simulator'
    | '/terms'
    | '/app/agent'
    | '/app/dashboard'
    | '/app/journal'
    | '/app/margin'
    | '/app/markets'
    | '/app/options'
    | '/app/portfolio'
    | '/app/settings'
    | '/app/simulator'
    | '/app/watchlist'
    | '/app'
    | '/app/stock/$symbol'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/simulator'
    | '/terms'
    | '/app/agent'
    | '/app/dashboard'
    | '/app/journal'
    | '/app/margin'
    | '/app/markets'
    | '/app/options'
    | '/app/portfolio'
    | '/app/settings'
    | '/app/simulator'
    | '/app/watchlist'
    | '/app/'
    | '/app/stock/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SimulatorRoute: typeof SimulatorRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/watchlist': {
      id: '/app/watchlist'
      path: '/watchlist'
      fullPath: '/app/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulator': {
      id: '/app/simulator'
      path: '/simulator'
      fullPath: '/app/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/options': {
      id: '/app/options'
      path: '/options'
      fullPath: '/app/options'
      preLoaderRoute: typeof AppOptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/markets': {
      id: '/app/markets'
      path: '/markets'
      fullPath: '/app/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/margin': {
      id: '/app/margin'
      path: '/margin'
      fullPath: '/app/margin'
      preLoaderRoute: typeof AppMarginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock/$symbol': {
      id: '/app/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/app/stock/$symbol'
      preLoaderRoute: typeof AppStockSymbolRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppJournalRoute: typeof AppJournalRoute
  AppMarginRoute: typeof AppMarginRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppOptionsRoute: typeof AppOptionsRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppStockSymbolRoute: typeof AppStockSymbolRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppJournalRoute: AppJournalRoute,
  AppMarginRoute: AppMarginRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppOptionsRoute: AppOptionsRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSimulatorRoute: AppSimulatorRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppStockSymbolRoute: AppStockSymbolRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SimulatorRoute: SimulatorRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
