/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWatchlistRouteImport } from './routes/app.watchlist'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppSimulatorRouteImport } from './routes/app.simulator'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScenariosRouteImport } from './routes/app.scenarios'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppOptionsRouteImport } from './routes/app.options'
import { Route as AppMarketsRouteImport } from './routes/app.markets'
import { Route as AppMarginRouteImport } from './routes/app.margin'
import { Route as AppJournalRouteImport } from './routes/app.journal'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppScenariosIndexRouteImport } from './routes/app.scenarios.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppStockSymbolRouteImport } from './routes/app.stock.$symbol'
import { Route as AppScenariosRunIdRouteImport } from './routes/app.scenarios.$runId'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'
import { Route as AppAdminUsersIndexRouteImport } from './routes/app.admin.users.index'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/app.admin.users.$userId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppOptionsRoute = AppOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppMarginRoute = AppMarginRouteImport.update({
  id: '/margin',
  path: '/margin',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosIndexRoute = AppScenariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppScenariosRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppStockSymbolRoute = AppStockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRunIdRoute = AppScenariosRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AppScenariosRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppAdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/agent': typeof AppAgentRoute
  '/app/coach': typeof AppCoachRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal': typeof AppJournalRoute
  '/app/margin': typeof AppMarginRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/options': typeof AppOptionsRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/scenarios': typeof AppScenariosRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/support': typeof AppSupportRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/app/scenarios/$runId': typeof AppScenariosRunIdRoute
  '/app/stock/$symbol': typeof AppStockSymbolRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/scenarios/': typeof AppScenariosIndexRoute
  '/app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/agent': typeof AppAgentRoute
  '/app/coach': typeof AppCoachRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal': typeof AppJournalRoute
  '/app/margin': typeof AppMarginRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/options': typeof AppOptionsRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/support': typeof AppSupportRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/scenarios/$runId': typeof AppScenariosRunIdRoute
  '/app/stock/$symbol': typeof AppStockSymbolRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/scenarios': typeof AppScenariosIndexRoute
  '/app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/app/admin/users': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/agent': typeof AppAgentRoute
  '/app/coach': typeof AppCoachRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/journal': typeof AppJournalRoute
  '/app/margin': typeof AppMarginRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/options': typeof AppOptionsRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/scenarios': typeof AppScenariosRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/support': typeof AppSupportRoute
  '/app/watchlist': typeof AppWatchlistRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/app/scenarios/$runId': typeof AppScenariosRunIdRoute
  '/app/stock/$symbol': typeof AppStockSymbolRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/scenarios/': typeof AppScenariosIndexRoute
  '/app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/simulator'
    | '/support'
    | '/terms'
    | '/app/admin'
    | '/app/agent'
    | '/app/coach'
    | '/app/dashboard'
    | '/app/journal'
    | '/app/margin'
    | '/app/markets'
    | '/app/options'
    | '/app/portfolio'
    | '/app/scenarios'
    | '/app/settings'
    | '/app/simulator'
    | '/app/support'
    | '/app/watchlist'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/users'
    | '/app/scenarios/$runId'
    | '/app/stock/$symbol'
    | '/app/admin/'
    | '/app/scenarios/'
    | '/app/admin/users/$userId'
    | '/app/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/simulator'
    | '/support'
    | '/terms'
    | '/app/agent'
    | '/app/coach'
    | '/app/dashboard'
    | '/app/journal'
    | '/app/margin'
    | '/app/markets'
    | '/app/options'
    | '/app/portfolio'
    | '/app/settings'
    | '/app/simulator'
    | '/app/support'
    | '/app/watchlist'
    | '/app'
    | '/app/admin/audit'
    | '/app/scenarios/$runId'
    | '/app/stock/$symbol'
    | '/app/admin'
    | '/app/scenarios'
    | '/app/admin/users/$userId'
    | '/app/admin/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/disclaimer'
    | '/privacy'
    | '/reset-password'
    | '/simulator'
    | '/support'
    | '/terms'
    | '/app/admin'
    | '/app/agent'
    | '/app/coach'
    | '/app/dashboard'
    | '/app/journal'
    | '/app/margin'
    | '/app/markets'
    | '/app/options'
    | '/app/portfolio'
    | '/app/scenarios'
    | '/app/settings'
    | '/app/simulator'
    | '/app/support'
    | '/app/watchlist'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/users'
    | '/app/scenarios/$runId'
    | '/app/stock/$symbol'
    | '/app/admin/'
    | '/app/scenarios/'
    | '/app/admin/users/$userId'
    | '/app/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SimulatorRoute: typeof SimulatorRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/watchlist': {
      id: '/app/watchlist'
      path: '/watchlist'
      fullPath: '/app/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulator': {
      id: '/app/simulator'
      path: '/simulator'
      fullPath: '/app/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios': {
      id: '/app/scenarios'
      path: '/scenarios'
      fullPath: '/app/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/options': {
      id: '/app/options'
      path: '/options'
      fullPath: '/app/options'
      preLoaderRoute: typeof AppOptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/markets': {
      id: '/app/markets'
      path: '/markets'
      fullPath: '/app/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/margin': {
      id: '/app/margin'
      path: '/margin'
      fullPath: '/app/margin'
      preLoaderRoute: typeof AppMarginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios/': {
      id: '/app/scenarios/'
      path: '/'
      fullPath: '/app/scenarios/'
      preLoaderRoute: typeof AppScenariosIndexRouteImport
      parentRoute: typeof AppScenariosRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/stock/$symbol': {
      id: '/app/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/app/stock/$symbol'
      preLoaderRoute: typeof AppStockSymbolRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios/$runId': {
      id: '/app/scenarios/$runId'
      path: '/$runId'
      fullPath: '/app/scenarios/$runId'
      preLoaderRoute: typeof AppScenariosRunIdRouteImport
      parentRoute: typeof AppScenariosRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/users/': {
      id: '/app/admin/users/'
      path: '/'
      fullPath: '/app/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/app/admin/users/$userId': {
      id: '/app/admin/users/$userId'
      path: '/$userId'
      fullPath: '/app/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
  }
}

interface AppAdminUsersRouteChildren {
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppScenariosRouteChildren {
  AppScenariosRunIdRoute: typeof AppScenariosRunIdRoute
  AppScenariosIndexRoute: typeof AppScenariosIndexRoute
}

const AppScenariosRouteChildren: AppScenariosRouteChildren = {
  AppScenariosRunIdRoute: AppScenariosRunIdRoute,
  AppScenariosIndexRoute: AppScenariosIndexRoute,
}

const AppScenariosRouteWithChildren = AppScenariosRoute._addFileChildren(
  AppScenariosRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAgentRoute: typeof AppAgentRoute
  AppCoachRoute: typeof AppCoachRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppJournalRoute: typeof AppJournalRoute
  AppMarginRoute: typeof AppMarginRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppOptionsRoute: typeof AppOptionsRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppScenariosRoute: typeof AppScenariosRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
  AppSupportRoute: typeof AppSupportRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppStockSymbolRoute: typeof AppStockSymbolRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAgentRoute: AppAgentRoute,
  AppCoachRoute: AppCoachRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppJournalRoute: AppJournalRoute,
  AppMarginRoute: AppMarginRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppOptionsRoute: AppOptionsRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppScenariosRoute: AppScenariosRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSimulatorRoute: AppSimulatorRoute,
  AppSupportRoute: AppSupportRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppStockSymbolRoute: AppStockSymbolRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SimulatorRoute: SimulatorRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
